### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by abh** [packethost/docker-machine-driver-packet#38] opened 2019-04-30 17:38 UTC
It'd be nice if the latest code was packaged up in a release since it seems like there are a few changes.

**Comment by abh** [comment] 2019-07-08 05:07
(specifically an update would allow the latest code to be included in Rancher)

**Comment by mclamb** [comment] 2019-07-12 22:02
Yes, that would be great for Rancher! I am now realizing that the node driver in Rancher is very old (0.1.4) and that the latest release 0.1.5 seems broken (see: #22 )

If we could get a new release that supports Ubuntu 18.04, Custom iPXE, and a recent version of RancherOS (the version on Packet now is very old at 0.7.1 whereas the latest version is 1.5.3) that would be very helpful.

Thanks

**Comment by abh** [comment] 2019-07-12 22:31
FWIW then when I tried 1.5.1 a little while back it didn't boot on systems with bonded interfaces. I'm not sure what the RancherOS roadmap/plans are and if it's worth fixing versus work on k3OS.

**Comment by mclamb** [comment] 2019-07-13 18:39
Good news. I've been in communication with Packet support and they have been very responsive and assigned an internal ticket to look into this, so looks like we might get movement on this soon.

**Comment by mclamb** [comment] 2019-07-13 18:41
Agreed that it would be cool to be able to deploy k3OS (and get a better handle on the RancherOS v. k3OS roadmap)... Perhaps if they add Custom iPXE support to the node driver then we can make it work in Rancher via already existing cluster import (or add logic to "detect" that k3OS already has K8s installed and does not need a deployment of RKE)

**Comment by mclamb** [comment] 2019-07-21 19:30
Interested in the work that @skbki has done on these forks in order to get the Packet driver updated and working as a Rancher Node Driver:

https://github.com/skbki/docker-machine-driver-packet
https://github.com/skbki/ui-driver-packet

I still can't quite get them working together in Rancher. I think the problem is that the author just copied the ui-driver-packet from the default UI, which doesn't work for the plugin-based URL.

Has anyone gotten this to work?

**Comment by jasmingacic** [comment] 2019-08-09 21:27
Once PR #41 gets merged we are planning to push the latest release.

**Comment by displague** [comment] 2020-11-19 19:20
https://github.com/packethost/docker-machine-driver-packet/releases/tag/v0.3.0 is available with the latest changes

**Closed as completed by displague** 2020-11-19 19:20 UTC
